### ISSUE TITLE
Typo in url of streamviewer

### ISSUE THREAD

**Issue by varsovik** [sassoftware/esp-kubernetes#1]
Hi,
I believe there's small typo in this url:
http://streamviewer.esp.esptestscot.sas.com/SASEventStreamProccessingStreamviewer
It should be:
http://streamviewer.esp.esptestscot.sas.com/SASEventStreamProcessingStreamviewer
Regards.

**Comment by katjam-sas** [comment]
Thank you for bringing this to our attention. The example client URLs have been updated now: the typo has been fixed and general adjustments have been made to the URL examples to make them more appropriate.
