### ISSUE TITLE
what role does the ESP operator run as?

### ISSUE THREAD

**Issue by onion1984** [sassoftware/esp-kubernetes#2]
Hi, if the customer enabled RBAC in the K8S environment, what role will the ESP operator run as? will it encounter access right issue when creating new Pods to run the ESP Server/Project?

**Comment by shuhuang2002** [comment]
Hi, ESP operator uses service account "esp-operator".  Yes, "esp-operator" needs RBAC setup correctly in order to access resources such as pods/services/endpoints, etc. Take a look at https://github.com/sassoftware/esp-kubernetes/blob/master/operator/templates/operator/role.yaml.
