### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/esp-kubernetes#3]
Env:
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

When running on Kubernettes 1.16 or later, the dodeploy fails with 3 messages
error: unable to recognize "/home/centos/esp-kubernetes-master/operator/deploy/meter.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
error: unable to recognize "/home/centos/esp-kubernetes-master/operator/deploy/fileb.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
error: unable to recognize "/home/centos/esp-kubernetes-master/operator/deploy/meteragent.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
.
1.16 stopped allowing the deprecated format for Deployment
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
DaemonSet, Deployment, StatefulSet, and ReplicaSet (in the extensions/v1beta1 and apps/v1beta2 API groups)
Migrate to use the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

I could resolve this by editing the 3 files above to specify:
apiVersion: apps/v1
kind: Deployment

**Comment by shuhuang2002** [comment]
Thanks Andy. I convert them to apps/v1 and pushed the change. I think we need to test it more before we claim it works on 1.16+ though.

**Comment by dancruz-sas** [comment]
Closing this issue as stale due to inactivity.
